version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    # restart: always
    environment: 
      - SQLITE3_DB=db.sqlite3  
    volumes:
      -  ./data/db:/root/db 
    # ports:
    #   - "8000:8000"
   


        